import { useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { EmptyState, errorMessage, PageHeader } from "../components/ui";
import { useResource } from "../hooks/useResource";
import { isDesktopRuntime } from "../lib/api";
import { revenueApi } from "../lib/revenueApi";
import type { RevenueOverview } from "../revenueTypes";
import "./revenue.css";

const label = (value: string) => value.replace(/_/g, " ");
export function revenueMoney(cents: number | null, currency: string | null): string {
  if (cents === null || !currency) return "Unknown";
  try { return new Intl.NumberFormat(undefined, { style: "currency", currency }).format(cents / 100); }
  catch { return `${(cents / 100).toFixed(2)} ${currency}`; }
}
const totals = (amounts: Record<string, number>, empty: string) => Object.keys(amounts).length ? Object.entries(amounts).map(([currency, cents]) => revenueMoney(cents, currency)).join(" · ") : empty;

export function RevenuePage() {
  const [demo, setDemo] = useState(false);
  const resource = useResource(() => revenueApi.overview(demo), [demo]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [selected, setSelected] = useState("");
  const [projectId, setProjectId] = useState("");
  const [clientFilter, setClientFilter] = useState("");
  const [typeFilter, setTypeFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [confidenceFilter, setConfidenceFilter] = useState("");
  const [dateFilter, setDateFilter] = useState("");
  const [answer, setAnswer] = useState("");
  const [draftBody, setDraftBody] = useState("");
  const [clarifying, setClarifying] = useState(false);
  const [correcting, setCorrecting] = useState(false);
  const [showSetup, setShowSetup] = useState(false);
  const data = resource.data?.demo === demo ? resource.data : undefined;
  const opportunity = data?.opportunities.find((item) => item.id === selected);
  const draft = data?.drafts.find((item) => item.opportunityId === selected);
  useEffect(() => { setDraftBody(draft?.body ?? ""); }, [draft?.id, draft?.body]);
  useEffect(() => { setSelected(""); setProjectId(""); setAnswer(""); setClarifying(false); setCorrecting(false); }, [demo]);
  const run = async (operation: () => Promise<RevenueOverview>) => {
    setBusy(true); setError("");
    try {
      const result = await operation();
      if (result.demo !== demo) throw new Error("Revenue response belongs to a different data scope. Reload this view.");
      resource.setData(result);
    }
    catch (cause) { setError(errorMessage(cause)); }
    finally { setBusy(false); }
  };
  const items = (data?.opportunities ?? []).filter((item) => (!clientFilter || item.clientName === clientFilter) && (!typeFilter || item.type === typeFilter) && (!statusFilter || item.status === statusFilter) && (!confidenceFilter || item.confidence >= Number(confidenceFilter)) && (!dateFilter || item.createdAt >= Date.parse(dateFilter) / 1000));
  return <div className="page revenue-page">
    <PageHeader eyebrow="Evidence → review → outcome" title="Revenue Intelligence" description="Review commercial commitments, clarify missing evidence, and prepare your next action." actions={isDesktopRuntime() && <><button className="ghost-button" disabled={busy} onClick={() => setDemo(!demo)}>{demo ? "Return to actual data" : "Open isolated demo"}</button><button className="primary-button" disabled={busy || !data} onClick={() => void run(() => revenueApi.analyze(demo))}>Analyze local evidence</button></>} />
    {!isDesktopRuntime() ? <EmptyState title="Open Revenue in the desktop app" detail="Commercial records and the isolated demo use the local database. Browser preview cannot connect sources or save revenue decisions." /> : <>
      <p className={`notice ${demo ? "info" : "ok"}`}>{demo ? "Isolated demo · Fictional clients and fixed timestamps. These records and metrics are separate from your actual data." : "Actual local data · Analysis and drafts stay on this Mac. Approval records review only; it does not send messages or issue invoices."}</p>
      {error && <p className="notice error" role="alert">{error}</p>}
      {resource.error && <p className="notice error" role="alert">{resource.error} <button onClick={() => void resource.reload()}>Retry</button></p>}
      {resource.loading && !data && <p role="status">Loading local revenue records…</p>}
      {demo && <button className="ghost-button" disabled={busy} onClick={() => void run(revenueApi.seedDemo)}>Load reproducible demo</button>}
      {data && <>
        <section className="revenue-metrics" aria-label="Revenue overview">
          {[["Open opportunities", data.metrics.open], ["Need clarification", data.metrics.needsClarification], ["Drafts awaiting review", data.metrics.draftsAwaitingReview], ["Resolved opportunities", data.metrics.resolved], ["Evidence-supported potential", totals(data.metrics.potentialByCurrency, "Unknown")], ["Recovery with user-checked receipts", totals(data.metrics.verifiedRecoveredByCurrency, "No verified payments")]].map(([name, value]) => <article key={name}><span>{name}</span><strong>{value}</strong></article>)}
        </section>
        {!!data.skillSuggestions?.length && <section className="revenue-panel" aria-label="Commercial Skill suggestions"><h2>Suggested commercial procedures</h2>{data.skillSuggestions.map((suggestion) => <article key={suggestion.projectId}><h3>{suggestion.title}</h3><p>{suggestion.description}</p><p>{suggestion.confirmedOpportunityCount} distinct confirmations in this project. Review the procedure in the existing Workflows and Skill tools; no executable Skill has been created.</p>{!demo && <a className="ghost-button" href="#/workflows">Review in Workflows (Labs)</a>}</article>)}</section>}
        <details className="revenue-panel"><summary>Operational metrics and attribution</summary><p>Reviewed: {data.metrics.reviewed} · Confirmed: {data.metrics.confirmed} · Dismissed: {data.metrics.dismissed} · Drafts approved: {data.metrics.draftsApproved} · Actions recorded: {data.metrics.actionsRecorded} · Payments confirmed: {data.metrics.paymentsConfirmed}</p><p>Recovery is based on user-attested external receipts, not independent connector verification. Potential value, approval, and invoice issuance are separate from payments. A subsequent payment does not prove Knov caused it.</p></details>
        {!demo && <section className="revenue-panel"><button className="ghost-button" aria-expanded={showSetup} onClick={() => setShowSetup(!showSetup)}>Clients, documents & sources</button>{showSetup && <>
          <form className="stack-form" onSubmit={(event) => { event.preventDefault(); const fields = new FormData(event.currentTarget); void run(() => revenueApi.createProject(String(fields.get("client")), String(fields.get("name")), String(fields.get("description")), String(fields.get("threads")).split(",").map((x) => x.trim()).filter(Boolean))); }}><h2>Create a client project</h2><div className="revenue-fields"><label>Client name<input name="client" required maxLength={160} /></label><label>Project name<input name="name" required maxLength={160} /></label><label>Description<input name="description" maxLength={2000} /></label><label>Linked work thread IDs (optional)<input name="threads" placeholder="Comma-separated existing thread IDs" /></label></div><button className="primary-button" disabled={busy}>Create project</button></form>
          <label>Selected client project<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Choose a project</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{data.clients.find((client) => client.id === project.clientId)?.name} · {project.name}</option>)}</select></label>
          <form className="stack-form" onSubmit={(event) => { event.preventDefault(); const fields = new FormData(event.currentTarget); const path = String(fields.get("path")).trim(); void run(() => path ? revenueApi.importFile(projectId, String(fields.get("title")), path) : revenueApi.importAgreement(projectId, String(fields.get("title")), String(fields.get("text")))); }}><h2>Import an agreement</h2><label>Document title<input name="title" required maxLength={160} /></label><label>Plain text or Markdown<textarea name="text" rows={5} maxLength={64000} /></label><label>Or local .txt, .md or text PDF path<input name="path" placeholder="/Users/you/Documents/agreement.pdf" /></label><p className="field-hint">Local extraction only. Scanned PDFs require OCR and will be reported as unsupported. Extracted terms remain source-backed candidates for review.</p><button className="primary-button" disabled={busy || !projectId}>Import into selected project</button></form>
          <details><summary>Review extracted agreements</summary>{data.agreements.filter((item) => item.projectId === projectId).map((item) => <article key={item.id}><strong>{item.title}</strong><pre>{JSON.stringify(item, null, 2)}</pre><form className="stack-form" onSubmit={(event) => { event.preventDefault(); const text = String(new FormData(event.currentTarget).get("text")); void run(() => invoke<RevenueOverview>("revenue_update_agreement", { agreementId: item.id, text })); }}><label>Correct reviewed agreement text<textarea name="text" defaultValue={String(item.text ?? "")} rows={5} required maxLength={64000} /></label><button className="ghost-button" disabled={busy}>Save agreement correction</button></form></article>)}</details>
          <EvidenceEntry projectId={projectId} busy={busy} run={run} />
          <details><summary>Review synchronized communications</summary><p>Communications are untrusted source content. Review the exact excerpt and classify it before analysis; no source message can authorize an action.</p>{data.evidence.filter((item) => item.projectId === projectId && item.kind === "communication").map((item) => <article className="revenue-evidence" key={item.id}><strong>{item.source} · {label(item.provenance)}</strong><blockquote>{item.excerpt}</blockquote><small>{item.sourceRef} · {new Date(item.occurredAt * 1000).toLocaleString()}</small><form className="stack-form" onSubmit={(e) => { e.preventDefault(); const fields = new FormData(e.currentTarget); const due = String(fields.get("due")); const amount = String(fields.get("amount")).trim(); void run(() => invoke<RevenueOverview>("revenue_classify_evidence", { evidenceId: item.id, kind: fields.get("kind"), dueAt: due ? Date.parse(due) / 1000 : null, amountCents: amount ? Math.round(Number(amount) * 100) : null, currency: amount ? String(fields.get("currency")) : null })); }}><label>Reviewed evidence type<select name="kind">{["request", "activity", "approval", "commitment", "milestone_accepted", "invoice", "billing_complete"].map((kind) => <option value={kind} key={kind}>{label(kind)}</option>)}</select></label><label>Explicit due date, if stated (your local time)<input name="due" type="datetime-local" /></label><label>Amount explicitly supported by this source<input name="amount" type="number" min="0" step="0.01" /></label><label>Currency<input name="currency" defaultValue="USD" pattern="[A-Z]{3}" maxLength={3} /></label><button className="ghost-button" disabled={busy}>Save source classification</button></form></article>)}</details>
          <RevenueSources projectId={projectId} refresh={() => void resource.reload()} />
        </>}</section>}
        <div className="revenue-layout"><section className="revenue-panel" aria-label="Opportunity inbox"><h2>Opportunity inbox</h2><div className="revenue-filters">
          <label>Client<select value={clientFilter} onChange={(e) => setClientFilter(e.target.value)}><option value="">All clients</option>{[...new Set(data.opportunities.map((item) => item.clientName))].map((name) => <option key={name}>{name}</option>)}</select></label>
          <label>Type<select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}><option value="">All types</option>{[...new Set(data.opportunities.map((item) => item.type))].map((type) => <option key={type} value={type}>{label(type)}</option>)}</select></label>
          <label>Status<select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="">All statuses</option>{[...new Set(data.opportunities.map((item) => item.status))].map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></label>
          <label>Confidence<select value={confidenceFilter} onChange={(e) => setConfidenceFilter(e.target.value)}><option value="">Any confidence</option><option value="0.8">At least 80%</option><option value="0.5">At least 50%</option></select></label><label>Detected on or after<input type="date" value={dateFilter} onChange={(e) => setDateFilter(e.target.value)} /></label>
        </div>{items.length ? items.map((item) => <button key={item.id} className="revenue-item" aria-pressed={selected === item.id} disabled={busy} onClick={() => { setSelected(item.id); setAnswer(""); setClarifying(false); setCorrecting(false); }}><small>{item.clientName} · {item.projectName}</small><strong>{item.title}</strong><span>{label(item.status)} · {Math.round(item.confidence * 100)}% confidence · {revenueMoney(item.amountCents, item.currency)}</span><span>{item.recommendedAction}</span></button>) : <EmptyState title="No opportunities in this view" detail={demo ? "Load the reproducible demo, or adjust your filters." : "Create a project, import an agreement and source evidence, then analyze. Missing billing records will be shown as uncertainty."} />}</section>
        <section className="revenue-panel revenue-detail" aria-label="Opportunity detail">{!opportunity ? <EmptyState title="Select an opportunity" detail="Inspect exact evidence and uncertainty before deciding what to do." /> : <>
          <span className="eyebrow">{label(opportunity.provenance)} · {label(opportunity.type)}</span><h2>{opportunity.title}</h2><p>{opportunity.explanation}</p><h3>Supporting evidence</h3>{opportunity.evidenceIds.map((id) => { const evidence = data.evidence.find((item) => item.id === id); return evidence ? <article className="revenue-evidence" key={id}><strong>{label(evidence.kind)} · {label(evidence.provenance)}</strong><blockquote>{evidence.excerpt}</blockquote><small>{evidence.source} · {evidence.sourceRef} · {new Date(evidence.occurredAt * 1000).toLocaleString()}</small></article> : <p key={id}>Evidence {id} is unavailable.</p>; })}
          <h3>Uncertainty</h3><ul>{opportunity.uncertainty.map((text) => <li key={text}>{text}</li>)}</ul><h3>Evidence that would disprove this</h3><ul>{opportunity.disproves.map((text) => <li key={text}>{text}</li>)}</ul><h3>Business impact</h3><p>Evidence-supported amount: <strong>{revenueMoney(opportunity.amountCents, opportunity.currency)}</strong>. This is potential value, pending commercial review.</p><h3>Recommended action</h3><p>{opportunity.recommendedAction}</p>
          <div className="revenue-actions"><button disabled={busy} className="ghost-button" onClick={() => void run(() => revenueApi.review(opportunity.id, "confirm"))}>Confirm</button><button disabled={busy} className="ghost-button" onClick={() => { setCorrecting(!correcting); setClarifying(false); }}>Correct</button><button disabled={busy} className="ghost-button" onClick={() => void run(() => revenueApi.review(opportunity.id, "dismiss"))}>Dismiss</button><button disabled={busy} className="ghost-button" onClick={() => { setClarifying(!clarifying); setCorrecting(false); }}>Ask Knov</button><button disabled={busy} className="primary-button" onClick={() => void run(() => revenueApi.prepare(opportunity.id))}>Prepare action</button></div>
          {(clarifying || correcting) && <form className="stack-form" onSubmit={(e) => { e.preventDefault(); void run(() => revenueApi.review(opportunity.id, correcting ? "correct" : "clarify", answer.trim())); }}><h3>{correcting ? "Correct this opportunity" : "Contextual clarification"}</h3><p>{opportunity.clarificationQuestion ?? "What evidence changes your understanding of this opportunity?"}</p>{!correcting && opportunity.type === "scope_change" && <label>Scope decision<select value={answer} onChange={(e) => setAnswer(e.target.value)}><option value="">Choose or explain below</option><option value="already_included">Already included</option><option value="separately_billable">Separately billable</option><option value="free_addition">Approved as a free addition</option><option value="not_sure">Not sure</option></select></label>}<label>Your answer<textarea value={answer} onChange={(e) => setAnswer(e.target.value)} maxLength={6000} rows={3} /></label><p className="field-hint">Saved using Workflow Discovery. Your statement is user-confirmed context, not independent financial verification.</p><button className="primary-button" disabled={busy || !answer.trim()}>Save clarification</button>{!demo && opportunity.interviewId && <a href="#/discovery">Open saved Workflow Discovery interview</a>}</form>}
          {draft && <section className="stack-form"><h3>{label(draft.kind)} draft · {label(draft.status)}</h3><label>Edit draft<textarea rows={12} value={draftBody} onChange={(e) => setDraftBody(e.target.value)} maxLength={30000} /></label><div className="revenue-actions"><button className="ghost-button" disabled={busy || !draftBody.trim()} onClick={() => void run(() => revenueApi.saveDraft(draft.id, draftBody))}>Save draft</button><button className="primary-button" disabled={busy || draft.status === "approved" || draft.body !== draftBody} onClick={() => void run(() => revenueApi.approveDraft(draft.id))}>Approve draft</button></div><p className="field-hint">Save edits before approval. Approval never sends the draft or marks an external action complete.</p></section>}
          <OutcomeEntry opportunityId={opportunity.id} busy={busy} run={run} />
          <h3>Outcome history</h3><p>Detected {new Date(opportunity.createdAt * 1000).toLocaleString()} · Current review: {label(opportunity.status)}</p>{draft && <p>Action prepared {new Date(draft.createdAt * 1000).toLocaleString()} · {draft.status === "approved" ? "Draft approved for human use; no external action taken" : "Awaiting draft review"}</p>}{data.outcomes.filter((item) => item.opportunityId === opportunity.id).map((item) => <article className="revenue-evidence" key={item.id}><strong>{label(item.kind)} · {item.verified ? "User-checked external evidence" : "Self-reported"}</strong><p>{item.evidence}</p><small>{revenueMoney(item.amountCents, item.currency)} · {new Date(item.createdAt * 1000).toLocaleString()}</small></article>)}
          <h3>Commercial workflow</h3><ol className="revenue-process" aria-label="Commercial workflow stages">{workflowStages(opportunity.evidenceIds.map((id) => data.evidence.find((item) => item.id === id)?.kind ?? ""), opportunity.status, draft?.status, data.outcomes.filter((item) => item.opportunityId === opportunity.id)).map(([stage, status]) => <li key={stage}><strong>{stage}</strong><span>{status}</span></li>)}</ol>
        </>}</section></div>
      </>}
    </>}
  </div>;
}
type Run = (operation: () => Promise<RevenueOverview>) => Promise<void>;
function OutcomeEntry({ opportunityId, busy, run }: { opportunityId: string; busy: boolean; run: Run }) {
  const [kind, setKind] = useState("actioned");
  const [amount, setAmount] = useState("");
  const [verified, setVerified] = useState(false);
  const canVerify = kind === "paid" && amount.trim() !== "" && Number(amount) > 0;
  return <form className="stack-form" onSubmit={(event) => { event.preventDefault(); const fields = new FormData(event.currentTarget); const amount = String(fields.get("amount")).trim(); void run(() => revenueApi.recordOutcome(opportunityId, String(fields.get("kind")), String(fields.get("evidence")), amount ? Math.round(Number(amount) * 100) : null, amount ? String(fields.get("currency")) : null, canVerify && verified)); }}><h3>Record what happened afterward</h3><label>Outcome<select name="kind" value={kind} onChange={(e) => { setKind(e.target.value); setVerified(false); }}><option value="actioned">Action actually completed</option><option value="invoiced">Invoice issued</option><option value="paid">Payment received</option><option value="not_paid">Not paid</option><option value="unknown">Unknown</option></select></label><label>Evidence and source reference<textarea name="evidence" required maxLength={6000} rows={3} placeholder="For example: receipt ID, payment date, and verified record location" /></label><div className="revenue-fields"><label>Amount (optional; currency units)<input name="amount" type="number" min="0" step="0.01" value={amount} onChange={(e) => { setAmount(e.target.value); setVerified(false); }} /></label><label>Currency<input name="currency" defaultValue="USD" pattern="[A-Z]{3}" maxLength={3} /></label></div><label className="revenue-check"><input type="checkbox" name="verified" disabled={!canVerify} checked={verified && canVerify} onChange={(e) => setVerified(e.target.checked)} /> I checked an external payment receipt and attest this recovery amount</label><p className="field-hint">Receipt verification is your attestation and is available only for a payment with an explicit amount. Knov does not independently validate the receipt. Invoicing does not establish payment or attribution.</p><button className="primary-button" disabled={busy}>Record outcome</button></form>;
}
function EvidenceEntry({ projectId, busy, run }: { projectId: string; busy: boolean; run: Run }) {
  return <details><summary>Add reviewed work or billing evidence</summary><form className="stack-form" onSubmit={(e) => { e.preventDefault(); const fields = new FormData(e.currentTarget); const due = String(fields.get("due")); void run(() => invoke<RevenueOverview>("revenue_add_evidence", { projectId, kind: fields.get("kind"), sourceRef: fields.get("source"), text: fields.get("text"), occurredAt: Date.parse(String(fields.get("occurred"))) / 1000, dueAt: due ? Date.parse(due) / 1000 : null, amountCents: String(fields.get("amount")).trim() ? Math.round(Number(fields.get("amount")) * 100) : null, currency: String(fields.get("amount")).trim() ? String(fields.get("currency")) : null })); }}><label>Kind<select name="kind">{["request", "activity", "approval", "milestone_accepted", "invoice", "commitment", "billing_complete"].map((kind) => <option value={kind} key={kind}>{label(kind)}</option>)}</select></label><label>Source reference<input name="source" required /></label><label>Exact evidence<textarea name="text" required rows={3} /></label><label>Occurred at (your local time)<input name="occurred" type="datetime-local" required /></label><label>Explicit commitment due date (optional, your local time)<input name="due" type="datetime-local" /></label><div className="revenue-fields"><label>Evidence-supported amount (optional)<input name="amount" type="number" min="0" step="0.01" /></label><label>Currency<input name="currency" defaultValue="USD" pattern="[A-Z]{3}" maxLength={3} /></label></div><p className="field-hint">Only mark billing complete when the imported billing records actually cover this project and period.</p><button className="primary-button" disabled={busy || !projectId}>Add evidence</button></form></details>;
}
interface SourceStatus { provider: string; connected: boolean; account: string | null; lastSync: number | null; scope: { query: string; after: number; before: number; channels: string[]; maxItems: number } | null }
function RevenueSources({ projectId, refresh }: { projectId: string; refresh: () => void }) {
  const [provider, setProvider] = useState("gmail");
  const [status, setStatus] = useState<SourceStatus>();
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [deleteSourceConfirmed, setDeleteSourceConfirmed] = useState(false);
  useEffect(() => { let active = true; setStatus(undefined); setError(""); setDeleteSourceConfirmed(false); void invoke<SourceStatus>("revenue_connector_status", { provider }).then((value) => { if (active) setStatus(value); }).catch((cause) => { if (active) setError(errorMessage(cause)); }); return () => { active = false; }; }, [provider]);
  const operate = async (operation: () => Promise<unknown>) => {
    setBusy(true); setError(""); setMessage("");
    try { await operation(); }
    catch (cause) { setError(errorMessage(cause)); }
    finally {
      try { setStatus(await invoke<SourceStatus>("revenue_connector_status", { provider })); }
      catch { setStatus(undefined); }
      refresh();
      setBusy(false);
    }
  };
  return <section className="revenue-sources"><h2>Authorized communication sources</h2><p>Read-only, selected sources. Credentials are stored in Keychain. No email sending or Slack posting.</p><label>Provider<select value={provider} disabled={busy} onChange={(e) => setProvider(e.target.value)}><option value="gmail">Gmail</option><option value="slack">Slack</option></select></label>{error && <p role="alert" className="notice error">{error}</p>}{message && <p role="status" className="notice info">{message}</p>}<p>{status?.connected ? `Connected: ${status.account ?? provider}` : "Disconnected · No live source is synchronized"}</p>{status?.scope && <pre>{JSON.stringify(status.scope, null, 2)}</pre>}{status?.lastSync && <p>Last sync: {new Date(status.lastSync * 1000).toLocaleString()}</p>}
    {!status?.connected ? <form className="stack-form" onSubmit={(e) => { e.preventDefault(); const fields = new FormData(e.currentTarget); const form = e.currentTarget; const token = String(fields.get("token")); const clientId = String(fields.get("clientId") ?? "").trim(); const clientSecret = String(fields.get("clientSecret") ?? "").trim() || null; void operate(async () => { await invoke(provider === "gmail" && clientId ? "revenue_gmail_oauth" : "revenue_connector_connect", { provider, token, clientId, clientSecret, authorized: fields.get("authorized") === "on", scope: { query: String(fields.get("query") ?? ""), channels: String(fields.get("channels") ?? "").split(",").map((item) => item.trim()).filter(Boolean), after: Date.parse(String(fields.get("after"))) / 1000, before: Date.parse(String(fields.get("before"))) / 1000, maxItems: Number(fields.get("limit")) } }); form.reset(); setMessage("Authorized scope saved. Sync reads only the selected sources."); }); }}>
      <p className="field-hint">Configure a provider application and authorize read-only access before connecting. See docs/revenue-connectors.md for OAuth setup. A Google Desktop client ID opens browser authorization; Slack requires a read-only authorized token. Credentials are never saved in browser storage.</p>{provider === "gmail" && <><label>Google Desktop OAuth client ID (preferred)<input name="clientId" placeholder="…apps.googleusercontent.com" /></label><label>Desktop client secret (optional, if required by your configuration)<input name="clientSecret" type="password" autoComplete="off" maxLength={8192} /></label></>}<label>{provider === "gmail" ? "Or an authorized access token" : "Authorized access token"}<input name="token" type="password" required={provider === "slack"} autoComplete="off" /></label>{provider === "gmail" ? <label>Gmail query<input name="query" required placeholder="from:client.example.com" /></label> : <label>Selected Slack channel IDs<input name="channels" required placeholder="C0123,C0456" /></label>}<div className="revenue-fields"><label>Read from (UTC date)<input type="date" name="after" required /></label><label>Read before (UTC date)<input type="date" name="before" required /></label></div><label>Maximum records per sync<input type="number" name="limit" min="1" max="100" defaultValue="50" required /></label><label className="revenue-check"><input name="authorized" type="checkbox" required /> I authorize this account and only the source scope above</label><button className="primary-button" disabled={busy}>Authorize selected scope</button>
    </form> : <div className="revenue-actions"><button className="primary-button" disabled={busy || !projectId} onClick={() => void operate(async () => { const result = await invoke<{ imported: number; truncated: boolean }>("revenue_connector_sync", { provider, projectId }); setMessage(`Imported ${result.imported} records${result.truncated ? "; selected limit reached, history may be incomplete" : ""}.`); })}>Sync to selected project</button><button className="ghost-button" disabled={busy} onClick={() => void operate(() => invoke("revenue_connector_disconnect", { provider, revoke: true }))}>Disconnect & revoke</button></div>}
    <details><summary>Delete imported {provider === "gmail" ? "Gmail" : "Slack"} content</summary><p>Removes this source's imported excerpts and copied content in dependent drafts. Financial review history remains. Disconnect first to prevent future imports.</p><label className="revenue-check"><input type="checkbox" checked={deleteSourceConfirmed} onChange={(event) => setDeleteSourceConfirmed(event.target.checked)} /> Delete this source's imported content from this Mac</label><button className="danger-button" disabled={busy || !deleteSourceConfirmed} onClick={() => void operate(async () => { await invoke("revenue_delete_source", { source: provider }); setDeleteSourceConfirmed(false); setMessage("Imported source content deleted from this Mac."); })}>Delete imported source content</button></details>
  </section>;
}

function workflowStages(kinds: string[], status: string, draftStatus: string | undefined, outcomes: {kind: string; verified: boolean}[]): [string, string][] {
 const outcome = (kind: string) => { const match = outcomes.find((item) => item.kind === kind); return match ? match.verified ? "Recorded · user-checked external evidence" : "Recorded · self-reported, unverified" : "Missing from available records"; };
 return [["Client request", kinds.includes("request") || kinds.includes("commitment") ? "Source evidence available" : "Missing from available records"], ["Work planned", "Unverified · no linked planning record"], ["Work performed", kinds.includes("activity") || kinds.includes("milestone_accepted") ? "Source evidence available · inspect excerpt" : "Missing from available records"], ["Commercial review", draftStatus === "approved" ? "Internal draft reviewed · no external action" : status === "confirmed" ? "User confirmed opportunity" : "Review needed"], ["Client approval", kinds.includes("approval") ? "Approval evidence available" : "Missing · may exist outside connected sources"], ["Invoice", outcome("invoiced")], ["Payment", outcome("paid")]];
}
