import type {
  ActivityEvent,
  AgentOverview,
  AgentRun,
  AutonomyOverview,
  BrowserProfile,
  DashboardData,
  ProfileData,
  SettingsData,
  PredictionDashboard,
  Skill,
  Workflow,
  WorkflowStep,
  WorkPrediction,
} from "../types";

const now = Date.now();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();
const secondsAgo = (minutes: number) => Math.floor((now - minutes * 60_000) / 1000);

export const mockActivity: ActivityEvent[] = [
  {
    id: "event-1",
    appName: "Google Chrome",
    pageTitle: "Tauri 2 — Security Capabilities",
    windowTitle: "Tauri 2 — Security Capabilities - Google Chrome",
    url: "https://v2.tauri.app/security/capabilities/",
    browserProfile: "Work",
    startedAt: minutesAgo(12),
    durationSeconds: 1_440,
    topic: "Knov implementation",
    source: "chrome",
  },
  {
    id: "event-2-save",
    appName: "Visual Studio Code",
    windowTitle: "Knov — apps/desktop/src/App.tsx",
    pageTitle: "apps/desktop/src/App.tsx",
    startedAt: minutesAgo(28),
    durationSeconds: 0,
    topic: "Knov implementation",
    source: "editor",
  },
  {
    id: "event-2",
    appName: "Visual Studio Code",
    windowTitle: "Knov — App.tsx",
    startedAt: minutesAgo(42),
    durationSeconds: 1_680,
    topic: "Knov implementation",
    source: "collector",
  },
  {
    id: "event-3",
    appName: "Notion",
    pageTitle: "Knov launch notes",
    url: "https://notion.so/example",
    browserProfile: "Work",
    startedAt: minutesAgo(78),
    durationSeconds: 1_260,
    topic: "Product planning",
    source: "chrome",
  },
  {
    id: "event-4",
    appName: "YouTube",
    pageTitle: "Building native macOS apps with Tauri",
    url: "https://youtube.com/watch?v=example",
    browserProfile: "Personal",
    startedAt: minutesAgo(110),
    durationSeconds: 980,
    topic: "Desktop development",
    source: "history",
  },
];

export const mockDashboard: DashboardData = {
  range: "today",
  trackedSeconds: 21_960,
  focusedSeconds: 16_740,
  activeTopics: [
    { name: "Software development", count: 18 },
    { name: "Planning and notes", count: 8 },
    { name: "Web research", count: 7 },
  ],
  appUsage: [
    { name: "Chrome", seconds: 7_900, percentage: 36, color: "#adff2f", detail: "42 pages" },
    { name: "VS Code", seconds: 6_140, percentage: 28, color: "#58c7ff", detail: "3 projects" },
    { name: "Notion", seconds: 3_520, percentage: 16, color: "#c6a8ff", detail: "8 pages" },
    { name: "Terminal", seconds: 2_420, percentage: 11, color: "#ffac66", detail: "7 sessions" },
    { name: "Other", seconds: 1_980, percentage: 9, color: "#78828f" },
  ],
  siteUsage: [
    { name: "github.com", seconds: 4_160, percentage: 31, color: "#adff2f" },
    { name: "tauri.app", seconds: 2_730, percentage: 20, color: "#58c7ff" },
    { name: "notion.so", seconds: 2_190, percentage: 16, color: "#c6a8ff" },
    { name: "youtube.com", seconds: 1_940, percentage: 14, color: "#ffac66" },
    { name: "Other", seconds: 2_620, percentage: 19, color: "#78828f" },
  ],
  recentActivity: mockActivity,
  insights: [
    {
      id: "insight-1",
      title: "Native desktop development",
      description: "Your research clustered around Tauri security, macOS permissions, and browser messaging.",
      metric: "18 resources",
      evidence: "Based on active page titles and URLs from the last 7 days.",
    },
    {
      id: "insight-2",
      title: "Focused implementation block",
      description: "Your longest uninterrupted focused session today was in VS Code.",
      metric: "1h 34m",
      evidence: "Foreground-app focus excluding idle and locked time.",
    },
    {
      id: "insight-3",
      title: "Video research",
      description: "Several active video pages were related to local AI and macOS development.",
      metric: "7 video pages",
      evidence: "This counts active pages, not completed videos.",
    },
  ],
  recommendations: [
    {
      id: "recommendation-1",
      kind: "continuity",
      title: "Continue the native collector",
      body: "Your recent work moved from product requirements into Tauri security research. The next coherent step is validating the macOS permission bridge.",
      evidence: "Tauri documentation, Xcode, and the Knov repository were your strongest recent cluster.",
      createdAt: minutesAgo(5),
    },
    {
      id: "recommendation-2",
      kind: "behavioral",
      title: "A short reset may help",
      body: "You have been active for a sustained block. Consider stepping away before the next implementation pass.",
      evidence: "1h 34m of continuous foreground activity with no idle period longer than five minutes.",
      createdAt: minutesAgo(5),
    },
  ],
};

export const mockProfile: ProfileData = {
  summary:
    "You are building Knov, a memory-efficient personal AI agent. Your recent work is concentrated on local-first architecture, selective memory retrieval, and measurable context reduction.",
  sections: [
    {
      id: "projects",
      title: "Active projects",
      items: [
        {
          id: "project-knov",
          label: "Knov",
          description: "Apple Silicon macOS alpha using Tauri, React, Rust, SQLite, and local browser-history import.",
          confidence: 0.99,
          provenance: "inferred",
        },
      ],
    },
    {
      id: "skills",
      title: "Skills and tools",
      items: [
        { id: "skill-ts", label: "TypeScript & React", confidence: 0.95, provenance: "inferred" },
        { id: "skill-ai", label: "AI-assisted product development", confidence: 0.88, provenance: "inferred" },
        { id: "skill-product", label: "Product specification", confidence: 0.84, provenance: "observed" },
      ],
    },
    {
      id: "truth",
      title: "Your corrections",
      items: [
        {
          id: "truth-local",
          label: "Knov is local-first",
          description: "Raw behavioral history must stay on this Mac.",
          provenance: "user",
        },
      ],
    },
  ],
  updatedAt: minutesAgo(5),
};

export const mockBrowsers: BrowserProfile[] = [
  {
    id: "chrome-default",
    browser: "Chrome",
    name: "Default",
    path: "~/Library/Application Support/Google/Chrome/Default",
    selected: true,
    support: "required",
  },
  {
    id: "chrome-profile-1",
    browser: "Chrome",
    name: "Work",
    path: "~/Library/Application Support/Google/Chrome/Profile 1",
    selected: true,
    support: "required",
  },
  {
    id: "safari-default",
    browser: "safari",
    name: "Safari",
    path: "~/Library/Safari",
    selected: false,
    support: "best-effort",
  },
];

export const mockSettings: SettingsData = {
  provider: "local",
  aiConfigured: false,
  hasProviderKey: true,
  localBaseUrl: "http://localhost:11434",
  localModel: null,
  labsEnabled: false,
  profileReady: true,
  appVersion: "0.2.0",
  behavioralGuidanceEnabled: true,
  predictionExperimentEnabled: false,
  predictionDisplayThreshold: 0.65,
  agentPaused: false,
  agentMaxActionsPerHour: 30,
  launchAtLogin: false,
  selectedBrowserProfileIds: ["chrome-default", "chrome-profile-1"],
  excludedApps: ["1Password"],
  excludedDomains: ["bank.example"],
  collectionStatus: {
    enabled: true,
    accessibilityGranted: false,
    degradedReasons: ["Accessibility permission is not granted."],
  },
};

export const mockPredictions: WorkPrediction[] = [
  {
    id: "prediction-provider-1",
    createdAt: secondsAgo(4),
    source: "provider",
    intent: "Continue validating the Knov permission bridge",
    nextAction: "Review the Tauri capability settings and continue the desktop implementation.",
    nextResource: {
      type: "url",
      label: "Tauri security capabilities",
      safeLocator: "https://v2.tauri.app/security/capabilities/",
    },
    threadId: "knov-implementation",
    confidence: 0.78,
    horizonMinutes: 20,
    reasoningSummary: "Your recent work stayed in the Knov implementation thread and moved between code and Tauri security guidance.",
    evidence: [
      "28 min in Visual Studio Code",
      "Recent Tauri security reference",
      "Same work thread across recent activity",
    ],
    evaluationStatus: "pending",
    expiresAt: secondsAgo(-16),
  },
  {
    id: "prediction-baseline-1",
    createdAt: secondsAgo(4),
    source: "heuristic",
    intent: "Return to Knov implementation",
    nextAction: "Resume the most recently active work thread.",
    threadId: "knov-implementation",
    confidence: 0.61,
    horizonMinutes: 20,
    reasoningSummary: "This was the most recently active thread.",
    evidence: ["Most recently active thread"],
    evaluationStatus: "pending",
    expiresAt: secondsAgo(-16),
  },
];

export const mockPredictionDashboard: PredictionDashboard = {
  enabled: false,
  predictions: mockPredictions,
  stats: {
    totalPredictions: 18,
    evaluatedPredictions: 14,
    matched: 7,
    partial: 4,
    missed: 3,
    providerTop1Accuracy: 0.64,
    baselineTop1Accuracy: 0.43,
    workflowTop1Accuracy: 0.69,
    highConfidenceAccuracy: 0.71,
    userPositiveFeedbackRate: 0.75,
    calibration: [
      { label: "Below 50%", minConfidence: 0, maxConfidence: 0.5, count: 3, meanConfidence: 0.42, observedAccuracy: 0.33 },
      { label: "50–65%", minConfidence: 0.5, maxConfidence: 0.65, count: 5, meanConfidence: 0.58, observedAccuracy: 0.4 },
      { label: "65–80%", minConfidence: 0.65, maxConfidence: 0.8, count: 4, meanConfidence: 0.72, observedAccuracy: 0.75 },
      { label: "80% and above", minConfidence: 0.8, maxConfidence: 1, count: 2, meanConfidence: 0.86, observedAccuracy: 1 },
    ],
  },
};

/* Autonomous work agent sample data ------------------------------------ */

const githubStep: WorkflowStep = {
  key: "web:github.com",
  kind: "web",
  category: "code-hosting",
  label: "github.com",
  title: "Review on github.com",
  resource: "https://github.com/Marstronix218/knov/issues",
  averageSeconds: 260,
};
const editorStep: WorkflowStep = {
  key: "app:visual studio code",
  kind: "app",
  category: "code",
  label: "Visual Studio Code",
  title: "Edit code in Visual Studio Code",
  resource: "Visual Studio Code",
  averageSeconds: 1_520,
};
const terminalStep: WorkflowStep = {
  key: "app:terminal",
  kind: "app",
  category: "terminal",
  label: "Terminal",
  title: "Run commands in Terminal",
  resource: "Terminal",
  averageSeconds: 310,
};

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-build-test",
    title: "Build and test · Knov desktop",
    generatedTitle: "Build and test · Knov desktop",
    status: "confirmed",
    active: true,
    steps: [githubStep, editorStep, terminalStep, { ...githubStep, averageSeconds: 140 }],
    stats: {
      occurrences: 11,
      distinctDays: 9,
      perWeek: 3.8,
      averageDurationSeconds: 2_460,
      completionRate: 0.79,
      typicalHour: 10,
      thread: "Knov desktop",
    },
    evidence: [
      { startedAt: secondsAgo(26 * 60), endedAt: secondsAgo(25 * 60), thread: "Knov desktop", details: ["github.com/Marstronix218/knov/issues/43", "Visual Studio Code", "Terminal", "github.com/Marstronix218/knov/pull/44"] },
      { startedAt: secondsAgo(50 * 60), endedAt: secondsAgo(49 * 60), thread: "Knov desktop", details: ["github.com/Marstronix218/knov/issues/41", "Visual Studio Code", "Terminal", "github.com/Marstronix218/knov/issues/41"] },
      { startedAt: secondsAgo(74 * 60), endedAt: secondsAgo(73 * 60), thread: "Knov desktop", details: ["github.com/Marstronix218/knov/issues/38", "Visual Studio Code", "Terminal", "github.com/Marstronix218/knov/pull/39"] },
    ],
    opportunity: {
      score: 0.74,
      frequency: 0.76,
      timeCost: 0.93,
      stability: 0.79,
      executability: 0.63,
      risk: 0.1,
      preparableSteps: 2,
      executableSteps: 1,
      estimatedMinutesSavedPerWeek: 5.7,
      surfaced: true,
      rationale: [
        "Seen 11 times on 9 days (about 3.8 per week).",
        "Takes about 41 min each time.",
        "Finished 79% of the times it was started.",
        "Knov can prepare 2 step(s) and run checks for 1 step(s).",
        "Skill runs so far: 6 of 7 completed, 0 rolled back.",
      ],
    },
    skillId: "skill-build-test",
    firstSeenAt: secondsAgo(26 * 24 * 60),
    lastSeenAt: secondsAgo(25 * 60),
    updatedAt: secondsAgo(30),
  },
  {
    id: "wf-research",
    title: "Research loop · Tauri security",
    generatedTitle: "Research loop · Tauri security",
    status: "discovered",
    active: true,
    steps: [
      { key: "search", kind: "search", category: "search", label: "Web search", title: "Search the web", averageSeconds: 40 },
      { key: "web:v2.tauri.app", kind: "web", category: "docs", label: "v2.tauri.app", title: "Read v2.tauri.app", resource: "https://v2.tauri.app/security/capabilities/", averageSeconds: 620 },
      { key: "web:github.com", kind: "web", category: "code-hosting", label: "github.com", title: "Review on github.com", resource: "https://github.com/tauri-apps/tauri/issues", averageSeconds: 300 },
    ],
    stats: { occurrences: 6, distinctDays: 5, perWeek: 2.1, averageDurationSeconds: 1_140, completionRate: 0.55, thread: "Tauri security" },
    evidence: [
      { startedAt: secondsAgo(2 * 24 * 60), endedAt: secondsAgo(2 * 24 * 60 - 18), thread: "Tauri security", details: ["Web search", "v2.tauri.app/security/capabilities", "github.com/tauri-apps/tauri/issues"] },
      { startedAt: secondsAgo(4 * 24 * 60), endedAt: secondsAgo(4 * 24 * 60 - 20), thread: "Tauri security", details: ["Web search", "v2.tauri.app/security/permissions", "github.com/tauri-apps/tauri/discussions"] },
    ],
    opportunity: {
      score: 0.52,
      frequency: 0.42,
      timeCost: 0.63,
      stability: 0.55,
      executability: 0.33,
      risk: 0.1,
      preparableSteps: 2,
      executableSteps: 0,
      estimatedMinutesSavedPerWeek: 1.1,
      surfaced: true,
      rationale: [
        "Seen 6 times on 5 days (about 2.1 per week).",
        "Takes about 19 min each time.",
        "Finished 55% of the times it was started.",
        "Knov can prepare 2 of these steps by opening them.",
      ],
    },
    firstSeenAt: secondsAgo(18 * 24 * 60),
    lastSeenAt: secondsAgo(2 * 24 * 60),
    updatedAt: secondsAgo(30),
  },
  {
    id: "wf-friday-report",
    title: "Reporting routine",
    generatedTitle: "Reporting routine",
    status: "discovered",
    active: true,
    steps: [
      { key: "web:docs.google.com/spreadsheets", kind: "web", category: "spreadsheet", label: "Google Sheets", title: "Update Google Sheets", resource: "https://docs.google.com/spreadsheets", averageSeconds: 900 },
      { key: "web:notion.so", kind: "web", category: "notes", label: "notion.so", title: "Write in notion.so", resource: "https://notion.so", averageSeconds: 700 },
      { key: "app:slack", kind: "app", category: "communication", label: "Slack", title: "Check Slack", resource: "Slack", averageSeconds: 240 },
    ],
    stats: { occurrences: 4, distinctDays: 4, perWeek: 1, averageDurationSeconds: 1_980, completionRate: 1, typicalWeekday: "Friday", typicalHour: 16 },
    evidence: [
      { startedAt: secondsAgo(7 * 24 * 60), endedAt: secondsAgo(7 * 24 * 60 - 33), details: ["docs.google.com/spreadsheets", "notion.so/weekly", "Slack"] },
    ],
    opportunity: {
      score: 0.46,
      frequency: 0.2,
      timeCost: 1,
      stability: 1,
      executability: 0.5,
      risk: 0.3,
      preparableSteps: 3,
      executableSteps: 0,
      estimatedMinutesSavedPerWeek: 0.8,
      surfaced: true,
      rationale: [
        "Seen 4 times on 4 days (about 1.0 per week).",
        "Takes about 33 min each time.",
        "Finished 100% of the times it was started.",
        "Knov can prepare 3 of these steps by opening them.",
        "Includes communication; Knov only opens it and never sends.",
      ],
    },
    firstSeenAt: secondsAgo(28 * 24 * 60),
    lastSeenAt: secondsAgo(7 * 24 * 60),
    updatedAt: secondsAgo(30),
  },
  {
    id: "wf-inbox",
    title: "Mail → github.com → Slack",
    generatedTitle: "Mail → github.com → Slack",
    status: "discovered",
    active: true,
    steps: [
      { key: "app:mail", kind: "app", category: "email", label: "Mail", title: "Handle email in Mail", resource: "Mail", averageSeconds: 200 },
      { ...githubStep, averageSeconds: 90 },
      { key: "app:slack", kind: "app", category: "communication", label: "Slack", title: "Check Slack", resource: "Slack", averageSeconds: 120 },
    ],
    stats: { occurrences: 3, distinctDays: 3, perWeek: 0.7, averageDurationSeconds: 410, completionRate: 0.38 },
    evidence: [],
    opportunity: {
      score: 0.21,
      frequency: 0.14,
      timeCost: 0.23,
      stability: 0.38,
      executability: 0.5,
      risk: 0.3,
      preparableSteps: 3,
      executableSteps: 0,
      estimatedMinutesSavedPerWeek: 0.5,
      surfaced: false,
      rationale: ["Seen 3 times on 3 days (about 0.7 per week)."],
    },
    firstSeenAt: secondsAgo(12 * 24 * 60),
    lastSeenAt: secondsAgo(3 * 24 * 60),
    updatedAt: secondsAgo(30),
  },
];

export const mockSkills: Skill[] = [
  {
    id: "skill-build-test",
    name: "Build and test · Knov desktop",
    description: "Learned from 11 observed runs of this workflow.",
    workflowId: "wf-build-test",
    thread: "Knov desktop",
    trigger: { kind: "context" },
    onException: "continue",
    enabled: true,
    steps: [
      { id: "step-1", title: "Review on github.com", category: "code-hosting", enabled: true, action: { type: "open_url", url: "https://github.com/Marstronix218/knov/issues", resolveDomain: "github.com" } },
      { id: "step-2", title: "Edit code in Visual Studio Code", category: "code", enabled: true, action: { type: "open_application", app: "Visual Studio Code" } },
      { id: "step-3", title: "Run `npm test` in knov", category: "terminal", enabled: true, action: { type: "run_checks", workspaceId: "ws-knov", preset: "npm-test" } },
      { id: "step-4", title: "Return to github.com", category: "code-hosting", enabled: true },
      { id: "brief", title: "Save a resume brief to Drafts", category: "notes", enabled: true, action: { type: "write_draft", template: "thread_brief" } },
    ],
    createdAt: secondsAgo(9 * 24 * 60),
    updatedAt: secondsAgo(2 * 24 * 60),
    lastTriggeredAt: secondsAgo(6),
    stats: { runs: 7, completed: 5, needsAttention: 1, failed: 1, rolledBack: 0, lastRunAt: secondsAgo(6) },
  },
];

export const mockRuns: AgentRun[] = [
  {
    id: "run-context-1",
    skillId: "skill-build-test",
    title: "Build and test · Knov desktop",
    origin: "context",
    status: "awaiting_approval",
    summary: "1 need attention · 1 done · 2 waiting for you",
    onException: "continue",
    state: {
      thread: "Knov desktop",
      goal: "Ship the Knov desktop alpha",
      workflow: "Build and test · Knov desktop (step 2 of 4)",
      recentSteps: ["Review on github.com", "Edit code in Visual Studio Code"],
    },
    manualSteps: ["Return to github.com"],
    createdAt: secondsAgo(6),
    actions: [
      {
        id: "act-open-issue",
        runId: "run-context-1",
        stepId: "step-1",
        position: 1,
        actionType: "open_url",
        title: "Review on github.com",
        riskClass: "ephemeral",
        targetLabel: "github.com/Marstronix218/knov/issues/43",
        rationale: "Reopens the latest github.com page from this thread, the next resource this workflow uses.",
        scopeKind: "skill",
        scopeValue: "skill-build-test",
        scopeLabel: "“Build and test · Knov desktop”",
        decision: "pending",
        decisionReason: "Background runs never open windows or apps on their own; approve to stage it now.",
        status: "awaiting_approval",
        preview: "https://github.com/Marstronix218/knov/issues/43",
        rollbackAvailable: false,
        canOpen: false,
        createdAt: secondsAgo(6),
      },
      {
        id: "act-open-editor",
        runId: "run-context-1",
        stepId: "step-2",
        position: 2,
        actionType: "open_application",
        title: "Edit code in Visual Studio Code",
        riskClass: "ephemeral",
        targetLabel: "Visual Studio Code",
        rationale: "Brings Visual Studio Code forward, as this workflow usually does at this step.",
        scopeKind: "skill",
        scopeValue: "skill-build-test",
        scopeLabel: "“Build and test · Knov desktop”",
        decision: "pending",
        decisionReason: "Knov asks before acting until you allow this kind of action.",
        status: "awaiting_approval",
        preview: "Open Visual Studio Code",
        rollbackAvailable: false,
        canOpen: false,
        createdAt: secondsAgo(6),
      },
      {
        id: "act-run-checks",
        runId: "run-context-1",
        stepId: "step-3",
        position: 3,
        actionType: "run_checks",
        title: "Run `npm test` in knov",
        riskClass: "ephemeral",
        targetLabel: "npm test in knov",
        rationale: "Runs `npm test` in knov so results are ready when you get there. Output stays on this Mac.",
        scopeKind: "workspace",
        scopeValue: "ws-knov",
        scopeLabel: "the knov workspace",
        decision: "auto",
        decisionReason: "Allowed by your grant for the knov workspace.",
        grantId: "grant-checks",
        status: "needs_attention",
        resultSummary: "Checks failed: `npm test` exited with 1",
        outputExcerpt: " ✓ src/lib/format.test.ts (4 tests)\n ✓ src/lib/api.test.ts (5 tests)\n ✗ src/App.test.tsx > dashboard > opens the latest web resource\n   AssertionError: expected 'Opening…' to contain 'Opened'\n Test Files  1 failed | 2 passed (3)\n      Tests  1 failed | 64 passed (65)",
        preview: "`npm test` in ~/Desktop/knov",
        verification: { passed: true, checks: ["`npm test` ran to completion in 6s", "Exit code 1 captured"] },
        rollbackAvailable: false,
        canOpen: false,
        createdAt: secondsAgo(6),
        startedAt: secondsAgo(6),
        finishedAt: secondsAgo(6),
      },
      {
        id: "act-brief",
        runId: "run-context-1",
        stepId: "brief",
        position: 4,
        actionType: "write_draft",
        title: "Save a resume brief to Drafts",
        riskClass: "draft",
        targetLabel: "Resume brief: Knov desktop",
        rationale: "Saves a Markdown draft in Knov's Drafts folder for you to review. Nothing is sent anywhere.",
        scopeKind: "skill",
        scopeValue: "skill-build-test",
        scopeLabel: "“Build and test · Knov desktop”",
        decision: "auto",
        decisionReason: "Allowed by your grant for “Build and test · Knov desktop”.",
        status: "succeeded",
        resultSummary: "Saved draft “Resume brief: Knov desktop”",
        preview: "# Resume brief: Knov desktop\n\n**Goal:** Ship the Knov desktop alpha (inferred)\n\n## Where you left off\n- Edit code in Visual Studio Code\n- Review on github.com\n\n## Likely next step\n- Run commands in Terminal (step 3 of 4)",
        verification: { passed: true, checks: ["Draft written inside Knov's Drafts folder", "Content hash verified after writing"] },
        rollbackAvailable: true,
        canOpen: true,
        createdAt: secondsAgo(6),
        startedAt: secondsAgo(6),
        finishedAt: secondsAgo(6),
      },
    ],
  },
  {
    id: "run-friday-1",
    skillId: "skill-weekly",
    title: "Weekly report prep",
    origin: "schedule",
    status: "completed",
    summary: "1 done",
    onException: "stop",
    state: { recentSteps: [] },
    manualSteps: ["Update Google Sheets", "Check Slack"],
    createdAt: secondsAgo(3 * 24 * 60),
    finishedAt: secondsAgo(3 * 24 * 60),
    actions: [
      {
        id: "act-weekly-checklist",
        runId: "run-friday-1",
        stepId: "brief",
        position: 1,
        actionType: "write_draft",
        title: "Save a checklist to Drafts",
        riskClass: "draft",
        targetLabel: "Checklist: Weekly report prep",
        rationale: "Saves a Markdown draft in Knov's Drafts folder for you to review. Nothing is sent anywhere.",
        scopeKind: "skill",
        scopeValue: "skill-weekly",
        scopeLabel: "“Weekly report prep”",
        decision: "auto",
        decisionReason: "Allowed by your grant for “Weekly report prep”.",
        status: "succeeded",
        resultSummary: "Saved draft “Checklist: Weekly report prep”",
        verification: { passed: true, checks: ["Draft written inside Knov's Drafts folder", "Content hash verified after writing"] },
        rollbackAvailable: true,
        canOpen: true,
        createdAt: secondsAgo(3 * 24 * 60),
      },
    ],
  },
];

export const mockAutonomy: AutonomyOverview = {
  paused: false,
  maxActionsPerHour: 30,
  autoActionsLastHour: 2,
  catalog: [
    { actionType: "open_url", title: "Open a web resource", description: "Opens a credential-free HTTP(S) page in your default browser.", riskClass: "ephemeral", riskLabel: "Ephemeral, local", defaultPolicy: "Ask until you allow it", interruptsUser: true, rollback: "Not needed; close the tab.", available: true },
    { actionType: "open_application", title: "Open an application", description: "Brings an installed Mac application to the front.", riskClass: "ephemeral", riskLabel: "Ephemeral, local", defaultPolicy: "Ask until you allow it", interruptsUser: true, rollback: "Not needed; quit or hide the app.", available: true },
    { actionType: "write_draft", title: "Write a local draft", description: "Saves a Markdown draft in Knov's own Drafts folder for you to review.", riskClass: "draft", riskLabel: "Draft for review", defaultPolicy: "Ask until you allow it", interruptsUser: false, rollback: "Knov deletes the draft if you have not edited it.", available: true },
    { actionType: "run_checks", title: "Run checks in a workspace", description: "Runs an allow-listed test command in a folder you approved. Output stays on this Mac.", riskClass: "ephemeral", riskLabel: "Ephemeral, local", defaultPolicy: "Ask until you allow it", interruptsUser: false, rollback: "Not needed; checks do not change Knov data.", available: true },
    { actionType: "commit_changes", title: "Commit code changes", description: "Creating commits or branches is not implemented in this alpha.", riskClass: "persistent_reversible", riskLabel: "Persistent, reversible", defaultPolicy: "Ask every time", interruptsUser: false, rollback: "Would require reverting the commit.", available: false },
    { actionType: "send_message", title: "Send a message or email", description: "Knov never sends messages, emails, or forms on your behalf in this alpha.", riskClass: "external_communication", riskLabel: "External communication", defaultPolicy: "Not available", interruptsUser: false, rollback: "Impossible once sent.", available: false },
    { actionType: "delete_or_pay", title: "Delete data, pay, or change security settings", description: "Destructive, financial, and credential actions are prohibited.", riskClass: "destructive", riskLabel: "Destructive or sensitive", defaultPolicy: "Not available", interruptsUser: false, rollback: "Often impossible.", available: false },
  ],
  grants: [
    { id: "grant-checks", actionType: "run_checks", scopeKind: "workspace", scopeValue: "ws-knov", scopeLabel: "the knov workspace", mode: "auto", source: "proposal", createdAt: secondsAgo(5 * 24 * 60) },
    { id: "grant-brief", actionType: "write_draft", scopeKind: "skill", scopeValue: "skill-build-test", scopeLabel: "“Build and test · Knov desktop”", mode: "auto", source: "approval", createdAt: secondsAgo(4 * 24 * 60) },
  ],
  proposals: [
    {
      actionType: "open_url",
      actionTitle: "Open a web resource",
      scopeKind: "skill",
      scopeValue: "skill-build-test",
      scopeLabel: "“Build and test · Knov desktop”",
      approvals: 6,
      message: "You approved “Open a web resource” for “Build and test · Knov desktop” 6 times and declined it 0 times. Allow it automatically there?",
    },
  ],
  workspaces: [
    { id: "ws-knov", label: "knov", path: "~/Desktop/knov", checkPresets: [{ id: "npm-test", label: "npm test" }], createdAt: secondsAgo(6 * 24 * 60) },
  ],
  detectedWorkspaces: [
    { label: "notes-app", path: "/Users/you/code/notes-app" },
  ],
  policy: [
    { actionType: "run_checks", actionTitle: "Run checks in a workspace", scopeLabel: "the knov workspace", approvals: 7, rejections: 0, automatic: 4, rolledBack: 0, tendency: "Runs automatically" },
    { actionType: "open_url", actionTitle: "Open a web resource", scopeLabel: "“Build and test · Knov desktop”", approvals: 6, rejections: 0, automatic: 0, rolledBack: 0, tendency: "You usually approve" },
    { actionType: "open_application", actionTitle: "Open an application", scopeLabel: "“Build and test · Knov desktop”", approvals: 3, rejections: 2, automatic: 0, rolledBack: 0, tendency: "Mixed" },
  ],
  metrics: {
    runs: 9,
    finishedRuns: 8,
    completedRuns: 7,
    taskCompletionRate: 0.875,
    actionsExecuted: 24,
    verifiedActions: 23,
    verificationRate: 0.958,
    approvalAcceptanceRate: 0.86,
    rollbackRate: 0.042,
    estimatedMinutesSaved: 19.5,
    activeAutoGrants: 2,
    highRiskActions: 0,
    actionsLast7Days: 11,
  },
};

export const mockAgentOverview: AgentOverview = {
  paused: false,
  awaitingCount: 1,
  opportunityCount: 2,
  workflowCount: 4,
  proposals: mockAutonomy.proposals,
  attention: [mockRuns[0], mockRuns[1]],
  state: {
    generatedAt: secondsAgo(0),
    activeThread: "Knov desktop",
    goal: {
      id: "goal-knov-desktop",
      title: "Ship the Knov desktop alpha",
      topic: "Knov desktop",
      status: "inferred",
      confidence: 0.83,
      evidence: [
        "Active on 9 of the last 14 days",
        "214 signals, 17h 00m observed, mostly in Visual Studio Code, github.com, Terminal",
        "Work looks like building software",
      ],
      activeDays: 9,
      observedSeconds: 61_200,
      lastActiveAt: secondsAgo(12),
    },
    goals: [
      {
        id: "goal-knov-desktop",
        title: "Ship the Knov desktop alpha",
        topic: "Knov desktop",
        status: "inferred",
        confidence: 0.83,
        evidence: ["Active on 9 of the last 14 days"],
        activeDays: 9,
        observedSeconds: 61_200,
        lastActiveAt: secondsAgo(12),
      },
      {
        id: "goal-tauri-security",
        title: "Research Tauri security",
        topic: "Tauri security",
        status: "inferred",
        confidence: 0.64,
        evidence: ["Active on 4 of the last 14 days"],
        activeDays: 4,
        observedSeconds: 9_400,
        lastActiveAt: secondsAgo(2 * 24 * 60),
      },
    ],
    recentSteps: [
      { label: "github.com", title: "Review on github.com", category: "code-hosting", at: secondsAgo(40), seconds: 240 },
      { label: "Visual Studio Code", title: "Edit code in Visual Studio Code", category: "code", at: secondsAgo(28), seconds: 1_500 },
    ],
    openResources: [
      { label: "github.com/Marstronix218/knov/issues/43", kind: "web", locator: "https://github.com/Marstronix218/knov/issues/43", at: secondsAgo(40) },
      { label: "Visual Studio Code", kind: "app", at: secondsAgo(28) },
    ],
    workflowProgress: {
      workflowId: "wf-build-test",
      title: "Build and test · Knov desktop",
      matchedSteps: 2,
      totalSteps: 4,
      nextStep: terminalStep,
      confidence: 0.82,
      skillId: "skill-build-test",
    },
    unresolved: [
      { kind: "awaiting_approval", title: "Build and test · Knov desktop", detail: "2 waiting for you", runId: "run-context-1", at: secondsAgo(6) },
      { kind: "workflow_in_progress", title: "Unfinished: Build and test · Knov desktop", detail: "Step 2 of 4 done; next is “Run commands in Terminal”.", at: secondsAgo(0) },
    ],
  },
};
